-- =============================================================================
-- TAX PORTAL - Supabase PostgreSQL Database Schema
-- สำหรับรันใน Supabase SQL Editor เพื่อสร้างตารางและนโยบายความปลอดภัย (RLS)
-- =============================================================================

-- 1. ตารางผู้ใช้งาน (users)
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    email TEXT,
    full_name TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    tax_id TEXT,
    phone TEXT,
    address TEXT,
    company_name TEXT,
    profile_pic TEXT,
    role TEXT DEFAULT 'member',
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. ตารางบันทึกการคำนวณภาษี (tax_records)
CREATE TABLE IF NOT EXISTS public.tax_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    tax_year TEXT NOT NULL DEFAULT '2567',
    taxpayer_type TEXT NOT NULL DEFAULT 'individual', -- 'individual' หรือ 'corporate'
    income_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    expense_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    allowance_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    summary_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    net_tax NUMERIC(12, 2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. ตารางติดต่อ/แจ้งปัญหา (support_tickets)
CREATE TABLE IF NOT EXISTS public.support_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    contact_name TEXT,
    contact_info TEXT,
    category TEXT NOT NULL,
    message TEXT NOT NULL,
    screenshot TEXT,
    status TEXT DEFAULT 'pending',
    admin_reply TEXT,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. ตารางบันทึกการตั้งค่าส่วนบุคคล (app_settings)
CREATE TABLE IF NOT EXISTS public.app_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE UNIQUE,
    theme TEXT DEFAULT 'amber',
    sound_enabled BOOLEAN DEFAULT true,
    sound_volume NUMERIC(3, 2) DEFAULT 0.5,
    language TEXT DEFAULT 'th',
    font_size TEXT DEFAULT 'normal',
    auto_save BOOLEAN DEFAULT true,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- สร้าง Indexes เพื่อความรวดเร็วในการค้นหา
CREATE INDEX IF NOT EXISTS idx_tax_records_user_id ON public.tax_records(user_id);
CREATE INDEX IF NOT EXISTS idx_tax_records_year ON public.tax_records(tax_year);
CREATE INDEX IF NOT EXISTS idx_support_tickets_status ON public.support_tickets(status);

-- เปิดใช้งาน Row Level Security (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tax_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;

-- นโยบาย RLS (ตัวอย่างสำหรับโหมด Anon/Public Key ให้ระบบเว็บสามารถบันทึกและอ่านข้อมูลได้)
DROP POLICY IF EXISTS "Public access to tax_records" ON public.tax_records;
CREATE POLICY "Public access to tax_records" ON public.tax_records FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public access to support_tickets" ON public.support_tickets;
CREATE POLICY "Public access to support_tickets" ON public.support_tickets FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public access to users" ON public.users;
CREATE POLICY "Public access to users" ON public.users FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public access to app_settings" ON public.app_settings;
CREATE POLICY "Public access to app_settings" ON public.app_settings FOR ALL USING (true) WITH CHECK (true);

-- เพิ่มบัญชีผู้ดูแลระบบตั้งต้น (Admin Seed)
INSERT INTO public.users (username, full_name, email, role, tax_id, company_name, password_hash)
VALUES (
    'admin',
    'ผู้ดูแลระบบ (Admin TAX PORTAL)',
    'admin@taxportal.go.th',
    'admin',
    '0105559999999',
    'สำนักงานพัฒนาธุรกรรมและบริการภาษี TAX PORTAL',
    '$2y$10$wT5gQd/5U41rKqgJb4E/veFw7i5k1y7m9H0pL2N3qX5rY6z8A' -- admin1234
) ON CONFLICT (username) DO NOTHING;
